'use strict';
// import bcrypt from "bcrypt"
const bcrypt = require("bcrypt");

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('users', [
      {
        name: 'Sudhakar',
        phone_number: 9876543210,
        gender: 'male',
        email: 'sudhakar@gmail.com',
        profile_picture: null,
        role: 'admin',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'Muthukumar',
        phone_number: 9876543211,
        gender: 'male',
        email: 'muthukumar@gmail.com',
        profile_picture: null,
        role: 'admin',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'Kumar',
        phone_number: '9500968610',
        gender: 'male',
        email: 'kumar@gmail.com',
        profile_picture: "photom2.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Priya Sharma',
        phone_number: '9500968611',
        gender: 'female',
        email: 'priya@gmail.com',
        profile_picture: "photof1.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Arun Raj',
        phone_number: '9500968612',
        gender: 'male',
        email: 'arun@gmail.com',
        profile_picture: "PHOTOM10.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Sneha Reddy',
        phone_number: '9500968613',
        gender: 'female',
        email: 'sneha@gmail.com',
        profile_picture: "photof2.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Karthik Mani',
        phone_number: '9500968614',
        gender: 'male',
        email: 'karthik@gmail.com',
        profile_picture: "photom4.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Divya Lakshmi',
        phone_number: '9500968615',
        gender: 'female',
        email: 'divya@gmail.com',
        profile_picture: "photof3.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Ravi Teja',
        phone_number: '9500968616',
        gender: 'male',
        email: 'ravi@gmail.com',
        profile_picture: "photom5.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Anitha Paul',
        phone_number: '9500968617',
        gender: 'female',
        email: 'anitha@gmail.com',
        profile_picture: "photof4.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Suresh Babu',
        phone_number: '9500968618',
        gender: 'male',
        email: 'suresh@gmail.com',
        profile_picture:"photom6.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Meena Krishnan',
        phone_number: '9500968619',
        gender: 'female',
        email: 'meena@gmail.com',
        profile_picture: "photof5.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Vignesh Kumar',
        phone_number: '9500968620',
        gender: 'male',
        email: 'vignesh@gmail.com',
        profile_picture: "photom7.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Keerthana Devi',
        phone_number: '9500968621',
        gender: 'female',
        email: 'keerthana@gmail.com',
        profile_picture: "photof15.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Manoj Prakash',
        phone_number: '9500968622',
        gender: 'male',
        email: 'manoj@gmail.com',
        profile_picture: "photom8.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Harini Selvam',
        phone_number: '9500968623',
        gender: 'female',
        email: 'harini@gmail.com',
        profile_picture: "photof7.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Ajith Kumar',
        phone_number: '9500968624',
        gender: 'male',
        email: 'ajith@gmail.com',
        profile_picture: "photom9.jpg",
        role: 'doctor',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      // ADD BELOW YOUR EXISTING DOCTOR USERS

      {
        name: 'Arun Kumar',
        phone_number: '9500968625',
        gender: 'male',
        email: 'patient1@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Priya Nair',
        phone_number: '9500968626',
        gender: 'female',
        email: 'patient2@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Karthik Raj',
        phone_number: '9500968627',
        gender: 'male',
        email: 'patient3@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Divya Sharma',
        phone_number: '9500968628',
        gender: 'female',
        email: 'patient4@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Rahul Verma',
        phone_number: '9500968629',
        gender: 'male',
        email: 'patient5@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Sneha Patel',
        phone_number: '9500968630',
        gender: 'female',
        email: 'patient6@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Vijay Kumar',
        phone_number: '9500968631',
        gender: 'male',
        email: 'patient7@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Anjali Singh',
        phone_number: '9500968632',
        gender: 'female',
        email: 'patient8@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Sathish Kumar',
        phone_number: '9500968633',
        gender: 'male',
        email: 'patient9@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Meera Joseph',
        phone_number: '9500968634',
        gender: 'female',
        email: 'patient10@gmail.com',
        profile_picture: null,
        role: 'patient',
        password: await bcrypt.hash("123456", 10),
        refresh_token: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('users', {});
  }
};